name: Wavefolder build

on:
  workflow_dispatch: # lets you run a build from the UI
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PLUGIN_NAME: Wavefolder
  BUILD_TYPE: Release

# jobs are run in paralell on different machines
# all steps run in series
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            pluginval-binary: pluginval.app/Contents/MacOS/pluginval
            ccache: ccache
            
          - name: Windows
            os: windows-latest
            pluginval-binary: ./pluginval.exe
            ccache: sccache

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup cache (ccache/sccache)
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.ccache }}
        variant: ${{ matrix.ccache }}

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      shell: bash
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER_LAUNCHER=${{ matrix.ccache }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.ccache }}

    - name: Build
      shell: bash
      run: cmake --build build --config $BUILD_TYPE --parallel 4
    
    # Upload artifacts
    - name: Upload artifacts (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ env.PLUGIN_NAME }}-macOS
        path: |
          build/Wavefolder_artefacts/Release/VST3/*.vst3
          build/Wavefolder_artefacts/Release/AU/*.component

    - name: Upload artifacts (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ env.PLUGIN_NAME }}-Windows
        path: |
          build/Wavefolder_artefacts/Release/VST3/*.vst3

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create zip files
      run: |
        zip -r ${{ env.PLUGIN_NAME }}-macOS.zip ${{ env.PLUGIN_NAME }}-macOS
        zip -r ${{ env.PLUGIN_NAME }}-Windows.zip ${{ env.PLUGIN_NAME }}-Windows
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.PLUGIN_NAME }}-macOS.zip
          ${{ env.PLUGIN_NAME }}-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}